import type { ResourceSchema } from '@/lib/resource-schema'

export const accountsReceivableSchema: ResourceSchema = {
  name: 'accountsReceivable',
  label: 'Accounts Receivable',
  pluralLabel: 'Accounts Receivable',
  module: 'finance',
  description: 'Track customer balances, credit limits, aging buckets, and collection history',
  iconName: 'CreditCard',
  primaryKey: 'id',
  titleField: 'invoiceNumber',
  defaultSort: {
    field: 'dueDate',
    direction: 'asc',
  },
  fields: [
    {
      name: 'invoiceNumber',
      label: 'Invoice Number',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. INV-2026-001',
    },
    {
      name: 'customerName',
      label: 'Customer Name',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'Customer / Client Name',
    },
    {
      name: 'customerCode',
      label: 'Customer Code',
      type: 'text',
      required: false,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. CUST-001',
    },
    {
      name: 'dueDate',
      label: 'Due Date',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'amount',
      label: 'Total Amount (USD)',
      type: 'currency',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'paidAmount',
      label: 'Paid Amount (USD)',
      type: 'currency',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'balanceDue',
      label: 'Balance Due (USD)',
      type: 'currency',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'agingCategory',
      label: 'Aging Category',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Current', '1-30 Days', '31-60 Days', '61-90 Days', '90+ Days'],
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Current', 'Overdue', 'Partial', 'Paid', 'Disputed'],
      badgeVariants: {
        Current: 'info',
        Overdue: 'destructive',
        Partial: 'warning',
        Paid: 'success',
        Disputed: 'outline',
      },
    },
  ],
}
