import type { ResourceSchema } from '@/lib/resource-schema'

export const auditLogSchema: ResourceSchema = {
  name: 'auditLog',
  label: 'Audit Log',
  pluralLabel: 'System Audit Logs',
  module: 'admin-settings',
  description: 'Track system activity, configuration changes, authentication events, and data mutations',
  iconName: 'FileSpreadsheet',
  primaryKey: 'id',
  titleField: 'timestamp',
  defaultSort: {
    field: 'timestamp',
    direction: 'desc',
  },
  fields: [
    {
      name: 'timestamp',
      label: 'Timestamp',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: false,
      showInDetail: true,
    },
    {
      name: 'userName',
      label: 'User Name',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: false,
      showInDetail: true,
    },
    {
      name: 'userRole',
      label: 'User Role',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: false,
      showInDetail: true,
    },
    {
      name: 'action',
      label: 'Action Event',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: false,
      showInDetail: true,
      options: ['CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'PERMISSION_CHANGE'],
      badgeVariants: {
        CREATE: 'success',
        UPDATE: 'info',
        DELETE: 'destructive',
        LOGIN: 'secondary',
        PERMISSION_CHANGE: 'warning',
      },
    },
    {
      name: 'module',
      label: 'Module',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: false,
      showInDetail: true,
    },
    {
      name: 'target',
      label: 'Target Entity',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: false,
      showInDetail: true,
    },
    {
      name: 'details',
      label: 'Activity Details',
      type: 'textarea',
      required: true,
      showInList: true,
      showInForm: false,
      showInDetail: true,
    },
    {
      name: 'ipAddress',
      label: 'IP Address',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: false,
      showInDetail: true,
    },
  ],
}
