import type { ResourceSchema } from '@/lib/resource-schema'

export const clientInvoiceSchema: ResourceSchema = {
  name: 'clientInvoice',
  label: 'Client Invoice',
  pluralLabel: 'Client Invoices',
  module: 'finance',
  description: 'Outbound freight and handling charges billed to export/import clients',
  iconName: 'FileCheck',
  primaryKey: 'id',
  titleField: 'invoiceNo',
  defaultSort: {
    field: 'dueDate',
    direction: 'asc',
  },
  fields: [
    {
      name: 'invoiceNo',
      label: 'Invoice No.',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. INV-2026-701',
    },
    {
      name: 'companyId',
      label: 'Billed Client',
      type: 'relation',
      relationTo: 'company',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'shipmentId',
      label: 'Shipment Consignment',
      type: 'relation',
      relationTo: 'shipment',
      required: false,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'status',
      label: 'Invoice Status',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Draft', 'Sent', 'Paid', 'Partially Paid', 'Overdue', 'Cancelled'],
      badgeVariants: {
        Draft: 'outline',
        Sent: 'info',
        Paid: 'success',
        'Partially Paid': 'secondary',
        Overdue: 'destructive',
        Cancelled: 'destructive',
      },
      defaultValue: 'Sent',
    },
    {
      name: 'issueDate',
      label: 'Issue Date',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'dueDate',
      label: 'Due Date',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'totalAmountUsd',
      label: 'Total Billed (USD)',
      type: 'currency',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      defaultValue: 5400,
    },
    {
      name: 'invoiceItems',
      label: 'Billed Fee Schedule',
      type: 'table',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetail: true,
      columns: [
        { name: 'description', label: 'Item Description', type: 'text', required: true },
        { name: 'amountUsd', label: 'Amount (USD)', type: 'number', required: true },
        { name: 'taxable', label: 'VAT Applicable', type: 'select', options: ['Yes (11%)', 'No (Exempt)', 'Zero-Rated'] },
      ],
    },
  ],
}
