import type { ResourceSchema } from '@/lib/resource-schema'

export const clientContractSchema: ResourceSchema = {
  name: 'clientContract',
  label: 'Client Contract',
  pluralLabel: 'Client Contracts',
  module: 'commercial',
  description: 'Manage long-term service level agreements, rate cards, and freight contracts',
  iconName: 'FileText',
  primaryKey: 'id',
  titleField: 'contractNo',
  defaultSort: {
    field: 'validUntil',
    direction: 'desc',
  },
  fields: [
    {
      name: 'contractNo',
      label: 'Contract No.',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. CTR-2026-088',
    },
    {
      name: 'companyId',
      label: 'Client Company',
      type: 'relation',
      relationTo: 'company',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'contractType',
      label: 'Contract Scope',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Annual Ocean Freight SLA', 'Air Freight Agreement', 'Customs Clearance Retainer', 'Full Logistics Contract'],
      badgeVariants: {
        'Annual Ocean Freight SLA': 'default',
        'Air Freight Agreement': 'info',
        'Customs Clearance Retainer': 'secondary',
        'Full Logistics Contract': 'success',
      },
      defaultValue: 'Annual Ocean Freight SLA',
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Active', 'Draft', 'Under Review', 'Expired', 'Terminated'],
      badgeVariants: {
        Active: 'success',
        Draft: 'outline',
        'Under Review': 'warning',
        Expired: 'destructive',
        Terminated: 'destructive',
      },
      defaultValue: 'Active',
    },
    {
      name: 'validFrom',
      label: 'Effective Date',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'validUntil',
      label: 'Expiry Date',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'committedVolumeTeu',
      label: 'Committed Volume (TEU / Year)',
      type: 'number',
      required: false,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      defaultValue: 500,
    },
    {
      name: 'paymentTerms',
      label: 'Payment Terms',
      type: 'select',
      required: true,
      showInList: false,
      showInForm: true,
      showInDetail: true,
      options: ['Net 15 Days', 'Net 30 Days', 'Net 60 Days', 'CBD (Cash Before Delivery)'],
      defaultValue: 'Net 30 Days',
    },
    {
      name: 'remarks',
      label: 'Contract Terms & Special Clauses',
      type: 'textarea',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetail: true,
      placeholder: 'Specify demurrage free days, peak season surcharges, bunker adjustments...',
    },
  ],
}
