import type { ResourceSchema } from '@/lib/resource-schema'

export const companySchema: ResourceSchema = {
  name: 'company',
  label: 'Client Account',
  pluralLabel: 'Client Accounts',
  module: 'commercial',
  description: 'Manage client accounts, registered office details, credit limits, and partner roles.',
  iconName: 'Building2',
  primaryKey: 'id',
  titleField: 'name',
  defaultSort: {
    field: 'name',
    direction: 'asc',
  },
  fields: [
    {
      name: 'code',
      label: 'Account Code',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. CMP-8801',
    },
    {
      name: 'name',
      label: 'Company Name',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. PT Samudera Logistics Express',
    },
    {
      name: 'partnerType',
      label: 'Partner Role',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: [
        'Exporter',
        'Importer',
        'Freight Forwarder',
        'Shipping Line',
        'Air Carrier',
        'Customs Broker',
        'Overseas Agent',
      ],
      badgeVariants: {
        Exporter: 'info',
        Importer: 'default',
        'Freight Forwarder': 'secondary',
        'Shipping Line': 'outline',
        'Air Carrier': 'warning',
        'Customs Broker': 'success',
        'Overseas Agent': 'secondary',
      },
    },
    {
      name: 'country',
      label: 'Country / Region',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Indonesia', 'Singapore', 'China', 'Germany', 'United States', 'Japan', 'Malaysia', 'Netherlands'],
    },
    {
      name: 'city',
      label: 'City',
      type: 'text',
      required: false,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. Jakarta / Surabaya',
    },
    {
      name: 'taxId',
      label: 'Tax ID / NPWP',
      type: 'text',
      required: false,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. 01.234.567.8-012.000',
    },
    {
      name: 'contactPerson',
      label: 'Contact Person',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. Hendra Wijaya',
    },
    {
      name: 'email',
      label: 'Email Address',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'contact@company.com',
    },
    {
      name: 'phone',
      label: 'Phone Number',
      type: 'text',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetail: true,
      placeholder: '+62 812-3456-7890',
    },
    {
      name: 'creditLimit',
      label: 'Credit Limit (USD)',
      type: 'currency',
      required: false,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      defaultValue: 50000,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Active', 'On Hold', 'Inactive'],
      badgeVariants: {
        Active: 'success',
        'On Hold': 'warning',
        Inactive: 'destructive',
      },
      defaultValue: 'Active',
    },
    {
      name: 'address',
      label: 'Registered Office Address',
      type: 'textarea',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetail: true,
      placeholder: 'Street name, building, floor, postal code...',
    },
  ],
}
