import type { ResourceSchema } from '@/lib/resource-schema'

export const costAccrualSchema: ResourceSchema = {
  name: 'costAccrual',
  label: 'Cost Accrual',
  pluralLabel: 'Cost Accruals',
  module: 'finance',
  description: 'Manage cost provisions and reconcile with vendor final bills',
  iconName: 'Anchor',
  primaryKey: 'id',
  titleField: 'id',
  defaultSort: {
    field: 'accrualDate',
    direction: 'desc',
  },
  fields: [
    {
      name: 'id',
      label: 'Accrual ID',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. ACC-2026-101',
    },
    {
      name: 'category',
      label: 'Cost Category',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: [
        'Ocean Freight Provision',
        'Port Terminal Handling',
        'Customs Duties & Clearing',
        'Feeder Barge Freight',
        'Trucking & Drayage',
      ],
    },
    {
      name: 'vendorName',
      label: 'Vendor Name',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'shipmentRef',
      label: 'Shipment Reference',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'blNumber',
      label: 'B/L Number',
      type: 'text',
      required: false,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'estimatedAmount',
      label: 'Estimated Amount (USD)',
      type: 'currency',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'actualAmount',
      label: 'Actual Bill (USD)',
      type: 'currency',
      required: false,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'variance',
      label: 'Variance (USD)',
      type: 'currency',
      required: false,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Provisioned', 'Partially Reconciled', 'Fully Reconciled'],
      badgeVariants: {
        Provisioned: 'warning',
        'Partially Reconciled': 'info',
        'Fully Reconciled': 'success',
      },
    },
  ],
}
