import type { ResourceSchema } from '@/lib/resource-schema'

export const generalLedgerSchema: ResourceSchema = {
  name: 'generalLedger',
  label: 'General Ledger Entry',
  pluralLabel: 'General Ledger Entries',
  module: 'finance',
  description: 'Double-entry journal vouchers and financial period postings',
  iconName: 'BookOpen',
  primaryKey: 'id',
  titleField: 'voucherNo',
  defaultSort: {
    field: 'postingDate',
    direction: 'desc',
  },
  fields: [
    {
      name: 'voucherNo',
      label: 'Voucher No.',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. JV-2026-0501',
    },
    {
      name: 'postingDate',
      label: 'Posting Date',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'period',
      label: 'Financial Period',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. 2026-Q1',
    },
    {
      name: 'accountCode',
      label: 'Account Code',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'accountName',
      label: 'Account Name',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'reference',
      label: 'Reference',
      type: 'text',
      required: false,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'debit',
      label: 'Debit (USD)',
      type: 'currency',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'credit',
      label: 'Credit (USD)',
      type: 'currency',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'status',
      label: 'Posting Status',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Posted', 'Unposted', 'Reversed'],
      badgeVariants: {
        Posted: 'success',
        Unposted: 'warning',
        Reversed: 'destructive',
      },
    },
  ],
}
