import type { ResourceSchema } from '@/lib/resource-schema'

export const moduleControlSchema: ResourceSchema = {
  name: 'moduleControl',
  label: 'ERP Module',
  pluralLabel: 'Module Controls',
  module: 'admin-settings',
  description: 'Manage ERP system module activation, route guards, and navigation visibility',
  iconName: 'Layers',
  primaryKey: 'id',
  titleField: 'name',
  defaultSort: {
    field: 'name',
    direction: 'asc',
  },
  fields: [
    {
      name: 'name',
      label: 'Module Name',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. Export & Import',
    },
    {
      name: 'category',
      label: 'Category',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: [
        'Core Operations',
        'Commercial & Sales',
        'Compliance & Customs',
        'Finance & Revenue',
        'System & ICT',
      ],
      badgeVariants: {
        'Core Operations': 'info',
        'Commercial & Sales': 'secondary',
        'Compliance & Customs': 'warning',
        'Finance & Revenue': 'success',
        'System & ICT': 'destructive',
      },
    },
    {
      name: 'url',
      label: 'Route URL',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: '/logistics/shipments',
    },
    {
      name: 'type',
      label: 'Module Type',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Core System', 'Operational View', 'Analytical Dashboard'],
      defaultValue: 'Operational View',
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Active', 'Disabled'],
      badgeVariants: {
        Active: 'success',
        Disabled: 'outline',
      },
      defaultValue: 'Active',
    },
  ],
}
