import type { ResourceSchema } from '@/lib/resource-schema'

export const roleSchema: ResourceSchema = {
  name: 'role',
  label: 'Role & Permission',
  pluralLabel: 'Roles & Permissions',
  module: 'admin-settings',
  description: 'Manage department security roles, access matrices, and operational capabilities',
  iconName: 'Shield',
  primaryKey: 'id',
  titleField: 'name',
  defaultSort: {
    field: 'name',
    direction: 'asc',
  },
  fields: [
    {
      name: 'name',
      label: 'Role Name',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. Senior Logistics Officer',
    },
    {
      name: 'department',
      label: 'Department',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. Operations / Freight Forwarding',
    },
    {
      name: 'description',
      label: 'Description',
      type: 'textarea',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'Brief scope of operational capabilities and permissions',
    },
    {
      name: 'authorityScope',
      label: 'Authority Level',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Full System Control', 'Department Restricted', 'View Only'],
      badgeVariants: {
        'Full System Control': 'destructive',
        'Department Restricted': 'info',
        'View Only': 'outline',
      },
      defaultValue: 'Department Restricted',
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Active', 'Archived'],
      badgeVariants: {
        Active: 'success',
        Archived: 'outline',
      },
      defaultValue: 'Active',
    },
  ],
}
