import type { ResourceSchema } from '@/lib/resource-schema'

export const serviceQuotationSchema: ResourceSchema = {
  name: 'serviceQuotation',
  label: 'Service Quotation',
  pluralLabel: 'Service Quotations',
  module: 'commercial',
  description: 'Freight rate offers and logistics service estimates for export/import clients',
  iconName: 'Calculator',
  primaryKey: 'id',
  titleField: 'quotationNo',
  defaultSort: {
    field: 'issuedDate',
    direction: 'desc',
  },
  fields: [
    {
      name: 'quotationNo',
      label: 'Quotation No.',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. QUO-2026-104',
    },
    {
      name: 'companyId',
      label: 'Prospect / Client',
      type: 'relation',
      relationTo: 'company',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'origin',
      label: 'Origin Port',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. Jakarta (IDTPP)',
    },
    {
      name: 'destination',
      label: 'Destination Port',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. Yokohama (JPYOK)',
    },
    {
      name: 'status',
      label: 'Quotation Status',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Draft', 'Sent', 'Accepted', 'Rejected', 'Expired'],
      badgeVariants: {
        Draft: 'outline',
        Sent: 'info',
        Accepted: 'success',
        Rejected: 'destructive',
        Expired: 'secondary',
      },
      defaultValue: 'Sent',
    },
    {
      name: 'issuedDate',
      label: 'Issued Date',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'validityDate',
      label: 'Valid Until',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'totalAmountUsd',
      label: 'Estimated Total (USD)',
      type: 'currency',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      defaultValue: 4800,
    },
    {
      name: 'chargeBreakdown',
      label: 'Charge Line Items',
      type: 'table',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetail: true,
      columns: [
        { name: 'serviceItem', label: 'Service Description', type: 'text', required: true },
        { name: 'unitRateUsd', label: 'Rate (USD)', type: 'number', required: true },
        { name: 'unit', label: 'Per Unit', type: 'select', options: ['Per Container (20ft)', 'Per Container (40ft)', 'Per CBM', 'Per BL', 'Per Shipment'] },
        { name: 'qty', label: 'Qty', type: 'number', required: true },
      ],
    },
  ],
}
