import type { ResourceSchema } from '@/lib/resource-schema'

export const shippingInstructionSchema: ResourceSchema = {
  name: 'shippingInstruction',
  label: 'Shipping Instruction',
  pluralLabel: 'Shipping Instructions',
  module: 'freight',
  description: 'Manage shipping instruction documents issued to ocean and air carriers',
  iconName: 'FileCheck',
  primaryKey: 'id',
  titleField: 'siNo',
  defaultSort: {
    field: 'siNo',
    direction: 'desc',
  },
  fields: [
    {
      name: 'siNo',
      label: 'SI Number',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. SI-2026-081',
    },
    {
      name: 'shipperName',
      label: 'Shipper Account',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. PT Export Jaya Utama',
    },
    {
      name: 'carrierName',
      label: 'Carrier Line',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. Maersk Line / COSCO',
    },
    {
      name: 'vesselVoyage',
      label: 'Vessel & Voyage',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. MSC MAYA v.024E',
    },
    {
      name: 'pol',
      label: 'POL Port',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. Tanjung Priok (IDTPP)',
    },
    {
      name: 'pod',
      label: 'POD Port',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. Singapore (SGSIN)',
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Draft', 'Submitted', 'Confirmed', 'Rejected'],
      badgeVariants: {
        Draft: 'secondary',
        Submitted: 'info',
        Confirmed: 'success',
        Rejected: 'destructive',
      },
      defaultValue: 'Submitted',
    },
  ],
}
