import type { ResourceSchema } from '@/lib/resource-schema'

export const shipmentSchema: ResourceSchema = {
  name: 'shipment',
  label: 'Freight Shipment',
  pluralLabel: 'Shipments',
  module: 'freight',
  description: 'Track sea, air, and land freight consignments and bill of lading documents',
  iconName: 'Ship',
  primaryKey: 'id',
  titleField: 'shipmentNo',
  defaultSort: {
    field: 'etd',
    direction: 'desc',
  },
  fields: [
    {
      name: 'shipmentNo',
      label: 'Shipment No.',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. SHP-2026-901',
    },
    {
      name: 'companyId',
      label: 'Consignee / Client',
      type: 'relation',
      relationTo: 'company',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'transportMode',
      label: 'Transport Mode',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Ocean Freight (FCL)', 'Ocean Freight (LCL)', 'Air Freight', 'Land Trucking'],
      badgeVariants: {
        'Ocean Freight (FCL)': 'default',
        'Ocean Freight (LCL)': 'secondary',
        'Air Freight': 'info',
        'Land Trucking': 'outline',
      },
      defaultValue: 'Ocean Freight (FCL)',
    },
    {
      name: 'status',
      label: 'Shipment Status',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: [
        'Booking Confirmed',
        'Cargo Received',
        'In Transit',
        'Customs Clearance',
        'Delivered',
        'Cancelled',
      ],
      badgeVariants: {
        'Booking Confirmed': 'outline',
        'Cargo Received': 'secondary',
        'In Transit': 'info',
        'Customs Clearance': 'warning',
        Delivered: 'success',
        Cancelled: 'destructive',
      },
      defaultValue: 'In Transit',
    },
    {
      name: 'incoterm',
      label: 'Incoterm',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['FOB', 'CIF', 'EXW', 'DDP', 'CFR', 'FCA', 'DAP'],
      defaultValue: 'FOB',
    },
    {
      name: 'originPort',
      label: 'Origin Port / Location',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. Tanjung Priok (IDTPP)',
    },
    {
      name: 'destinationPort',
      label: 'Destination Port / Location',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. Singapore (SGSIN)',
    },
    {
      name: 'etd',
      label: 'ETD (Departure)',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'eta',
      label: 'ETA (Arrival)',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'blNumber',
      label: 'B/L or HBL Number',
      type: 'text',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. MAEU9823411',
    },
    {
      name: 'vesselFlight',
      label: 'Vessel / Voyage / Flight',
      type: 'text',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. MSC MAYA v.024E',
    },
    {
      name: 'totalWeightKg',
      label: 'Gross Weight (KG)',
      type: 'number',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetail: true,
      defaultValue: 12500,
    },
    {
      name: 'totalVolumeCbm',
      label: 'Volume (CBM)',
      type: 'number',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetail: true,
      defaultValue: 45.5,
    },
    {
      name: 'freightCharge',
      label: 'Freight Value (USD)',
      type: 'currency',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      defaultValue: 3500,
    },
    {
      name: 'cargoItems',
      label: 'Cargo Item Manifest',
      type: 'table',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetail: true,
      columns: [
        { name: 'description', label: 'Item Description', type: 'text', required: true },
        { name: 'hsCode', label: 'HS Code', type: 'text' },
        { name: 'qty', label: 'Qty', type: 'number', required: true },
        { name: 'unit', label: 'Unit', type: 'select', options: ['PCS', 'CTN', 'PLT', 'DRUM', 'BAG'] },
        { name: 'weightKg', label: 'Weight (KG)', type: 'number' },
      ],
    },
  ],
}
