import type { ResourceSchema } from '@/lib/resource-schema'

export const userAccountSchema: ResourceSchema = {
  name: 'userAccount',
  label: 'User Account',
  pluralLabel: 'User Accounts',
  module: 'admin-settings',
  description: 'Manage corporate user accounts, department authorizations, and position security levels',
  iconName: 'Users',
  primaryKey: 'id',
  titleField: 'name',
  defaultSort: {
    field: 'name',
    direction: 'asc',
  },
  fields: [
    {
      name: 'name',
      label: 'Full Name',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. Fadhlur Rahman',
    },
    {
      name: 'email',
      label: 'Corporate Email',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. fdrahman@rexcorp.id',
    },
    {
      name: 'department',
      label: 'Department',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: [
        'ICT & Systems Administration',
        'Operations / Freight Forwarding',
        'Compliance / Customs Clearance',
        'Finance & Revenue',
        'Commercial & Sales',
        'General Operations',
      ],
    },
    {
      name: 'position',
      label: 'Job Position',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. Chief ICT Administrator',
    },
    {
      name: 'roleName',
      label: 'Assigned Role',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: [
        'ICT Admin (Full Control)',
        'Logistics & Freight Specialist',
        'Customs & Compliance Officer',
        'Finance & Accounting Lead',
        'Commercial Account Executive',
      ],
      badgeVariants: {
        'ICT Admin (Full Control)': 'destructive',
        'Logistics & Freight Specialist': 'info',
        'Customs & Compliance Officer': 'warning',
        'Finance & Accounting Lead': 'success',
        'Commercial Account Executive': 'secondary',
      },
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Active', 'Inactive', 'Suspended'],
      badgeVariants: {
        Active: 'success',
        Inactive: 'outline',
        Suspended: 'destructive',
      },
      defaultValue: 'Active',
    },
    {
      name: 'lastActive',
      label: 'Last Active',
      type: 'text',
      required: false,
      showInList: true,
      showInForm: false,
      showInDetail: true,
      placeholder: '2026-08-03 08:30 WIB',
    },
  ],
}
