import type { ResourceSchema } from '@/lib/resource-schema'

export const vendorBillSchema: ResourceSchema = {
  name: 'vendorBill',
  label: 'Vendor Bill',
  pluralLabel: 'Vendor Bills',
  module: 'finance',
  description: 'Invoices received from shipping lines, truckers, port authorities, and overseas agents',
  iconName: 'Receipt',
  primaryKey: 'id',
  titleField: 'billNo',
  defaultSort: {
    field: 'dueDate',
    direction: 'asc',
  },
  fields: [
    {
      name: 'billNo',
      label: 'Vendor Bill No.',
      type: 'text',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      placeholder: 'e.g. VBL-2026-302',
    },
    {
      name: 'companyId',
      label: 'Vendor / Carrier',
      type: 'relation',
      relationTo: 'company',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'shipmentId',
      label: 'Related Shipment',
      type: 'relation',
      relationTo: 'shipment',
      required: false,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'status',
      label: 'Payment Status',
      type: 'select',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      options: ['Unpaid', 'Partially Paid', 'Paid', 'Overdue', 'Under Dispute'],
      badgeVariants: {
        Unpaid: 'warning',
        'Partially Paid': 'info',
        Paid: 'success',
        Overdue: 'destructive',
        'Under Dispute': 'destructive',
      },
      defaultValue: 'Unpaid',
    },
    {
      name: 'billDate',
      label: 'Bill Date',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'dueDate',
      label: 'Due Date',
      type: 'date',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
    },
    {
      name: 'totalAmountUsd',
      label: 'Total Payable (USD)',
      type: 'currency',
      required: true,
      showInList: true,
      showInForm: true,
      showInDetail: true,
      defaultValue: 2800,
    },
    {
      name: 'notes',
      label: 'Payment Notes & Bank Reference',
      type: 'textarea',
      required: false,
      showInList: false,
      showInForm: true,
      showInDetail: true,
      placeholder: 'Enter vendor IBAN, payment reference code...',
    },
  ],
}
