import { useState, useEffect } from 'react'

export interface ResourceRecord {
  id: string
  createdBy?: string
  createdAt?: string
  updatedBy?: string
  updatedAt?: string
  [key: string]: any
}

// Current Active Session User (defaults to Fadhlur Rahman - Manager ICT, or active operator)
let currentSessionUser = 'Fadhlur Rahman (ICT Manager)'

export function getCurrentSessionUser(): string {
  return currentSessionUser
}

export function setCurrentSessionUser(userNameWithTitle: string): void {
  currentSessionUser = userNameWithTitle
}

// Synchronized mock data for metadata-driven ERP One
const initialData: Record<string, ResourceRecord[]> = {
  company: [
    {
      id: 'CMP-8801',
      code: 'CMP-8801',
      name: 'PT Samudera Export Indonesia',
      partnerType: 'Exporter',
      country: 'Indonesia',
      city: 'Jakarta Utara',
      taxId: '01.889.321.4-042.000',
      contactPerson: 'Budi Santoso',
      email: 'budi@samudera-export.co.id',
      phone: '+62 21 8892 1100',
      creditLimit: 150000,
      status: 'Active',
      address: 'Jl. Raya Tanjung Priok No. 88, Jakarta Utara, 14310',
      createdBy: 'Aditia Saputra (Account Officer)',
      createdAt: '2026-07-01 09:15 WIB',
      updatedBy: 'Budi Pratama (Marketing Manager)',
      updatedAt: '2026-08-01 14:20 WIB',
    },
    {
      id: 'CMP-8802',
      code: 'CMP-8802',
      name: 'Global Trading Pacific Pte Ltd',
      partnerType: 'Importer',
      country: 'Singapore',
      city: 'Singapore',
      taxId: '201988219M',
      contactPerson: 'David Chen',
      email: 'david.chen@gtpacific.sg',
      phone: '+65 6789 1234',
      creditLimit: 250000,
      status: 'Active',
      address: '10 Anson Road #14-02 International Plaza, Singapore 079903',
      createdBy: 'Aditia Saputra (Account Officer)',
      createdAt: '2026-07-05 11:30 WIB',
      updatedBy: 'Aditia Saputra (Account Officer)',
      updatedAt: '2026-08-02 10:05 WIB',
    },
    {
      id: 'CMP-8803',
      code: 'CMP-8803',
      name: 'Ocean Line Logistics GmbH',
      partnerType: 'Shipping Line',
      country: 'Germany',
      city: 'Hamburg',
      taxId: 'DE812345678',
      contactPerson: 'Klaus Weber',
      email: 'agency@oceanline-hamburg.de',
      phone: '+49 40 3381 00',
      creditLimit: 500000,
      status: 'Active',
      address: 'Hafenstraße 12, 20359 Hamburg, Germany',
      createdBy: 'Kevin Nugraha (Pricing & Vendor Officer)',
      createdAt: '2026-06-15 13:45 WIB',
      updatedBy: 'Farhan Hidayat (Procurement Manager)',
      updatedAt: '2026-07-28 16:00 WIB',
    },
    {
      id: 'CMP-8804',
      code: 'CMP-8804',
      name: 'Nusantara Customs Agency',
      partnerType: 'Customs Broker',
      country: 'Indonesia',
      city: 'Surabaya',
      taxId: '02.112.443.1-605.000',
      contactPerson: 'Dewi Lestari',
      email: 'dewi@nusantara-customs.co.id',
      phone: '+62 31 5543 210',
      creditLimit: 30000,
      status: 'Active',
      address: 'Jl. Perak Timur No. 42, Surabaya, Jawa Timur',
      createdBy: 'Hendra Kurniawan (Customs Clearance Officer)',
      createdAt: '2026-06-20 08:30 WIB',
      updatedBy: 'Hendra Kurniawan (Customs Clearance Officer)',
      updatedAt: '2026-07-30 09:12 WIB',
    },
  ],
  serviceQuotation: [
    {
      id: 'QUO-2026-104',
      quotationNo: 'QUO-2026-104',
      companyId: 'CMP-8801',
      origin: 'Tanjung Priok (IDTPP)',
      destination: 'Singapore (SGSIN)',
      status: 'Accepted',
      issuedDate: '2026-07-15',
      validityDate: '2026-08-15',
      totalAmountUsd: 4800,
      chargeBreakdown: [
        { serviceItem: 'Ocean Freight 40ft High Cube', unitRateUsd: 3800, unit: 'Per Container (40ft)', qty: 1 },
        { serviceItem: 'Terminal Handling Charge (THC)', unitRateUsd: 450, unit: 'Per Container (40ft)', qty: 1 },
        { serviceItem: 'Bill of Lading Documentation Fee', unitRateUsd: 150, unit: 'Per BL', qty: 1 },
        { serviceItem: 'Customs Clearance Admin', unitRateUsd: 400, unit: 'Per Shipment', qty: 1 },
      ],
      createdBy: 'Budi Pratama (Marketing Manager)',
      createdAt: '2026-07-15 10:00 WIB',
      updatedBy: 'Aditia Saputra (Account Officer)',
      updatedAt: '2026-07-18 15:30 WIB',
    },
    {
      id: 'QUO-2026-105',
      quotationNo: 'QUO-2026-105',
      companyId: 'CMP-8802',
      origin: 'Soekarno-Hatta (CGK)',
      destination: 'Hamburg (HAM)',
      status: 'Sent',
      issuedDate: '2026-07-28',
      validityDate: '2026-08-28',
      totalAmountUsd: 9200,
      createdBy: 'Aditia Saputra (Account Officer)',
      createdAt: '2026-07-28 09:15 WIB',
      updatedBy: 'Aditia Saputra (Account Officer)',
      updatedAt: '2026-07-28 09:15 WIB',
    },
  ],
  clientContract: [
    {
      id: 'CTR-2026-088',
      contractNo: 'CTR-2026-088',
      companyId: 'CMP-8801',
      quotationId: 'QUO-2026-104',
      contractType: 'Annual Ocean Freight SLA',
      status: 'Active',
      validFrom: '2026-01-01',
      validUntil: '2026-12-31',
      committedVolumeTeu: 600,
      paymentTerms: 'Net 30 Days',
      remarks: 'Free demurrage: 14 days at Tanjung Priok and Tanjung Perak. Fixed rate card for FEU containers.',
      createdBy: 'Aditia Saputra (Account Officer)',
      createdAt: '2026-07-19 11:00 WIB',
      updatedBy: 'Budi Pratama (Marketing Manager)',
      updatedAt: '2026-07-20 09:45 WIB',
    },
    {
      id: 'CTR-2026-089',
      contractNo: 'CTR-2026-089',
      companyId: 'CMP-8802',
      quotationId: 'QUO-2026-105',
      contractType: 'Full Logistics Contract',
      status: 'Active',
      validFrom: '2026-03-15',
      validUntil: '2027-03-14',
      committedVolumeTeu: 1200,
      paymentTerms: 'Net 15 Days',
      remarks: 'Includes door-to-door delivery in Singapore and customs brokerage handling.',
      createdBy: 'Aditia Saputra (Account Officer)',
      createdAt: '2026-07-29 14:00 WIB',
      updatedBy: 'Aditia Saputra (Account Officer)',
      updatedAt: '2026-07-29 14:00 WIB',
    },
  ],
  shippingInstruction: [
    {
      id: 'SI-2026-081',
      siNo: 'SI-2026-081',
      companyId: 'CMP-8801',
      quotationId: 'QUO-2026-104',
      contractId: 'CTR-2026-088',
      shipmentId: 'SHP-2026-901',
      shipperName: 'PT Samudera Export Indonesia',
      carrierName: 'Ocean Line Logistics GmbH',
      vesselVoyage: 'MSC MAYA v.024E',
      pol: 'Tanjung Priok (IDTPP)',
      pod: 'Singapore (SGSIN)',
      status: 'Confirmed',
      createdBy: 'Rizky Pratama (Export Officer)',
      createdAt: '2026-07-28 10:15 WIB',
      updatedBy: 'Bambang Sugianto (Operation Manager)',
      updatedAt: '2026-07-29 16:20 WIB',
    },
    {
      id: 'SI-2026-082',
      siNo: 'SI-2026-082',
      companyId: 'CMP-8802',
      quotationId: 'QUO-2026-105',
      contractId: 'CTR-2026-089',
      shipmentId: 'SHP-2026-902',
      shipperName: 'Global Trading Pacific Pte Ltd',
      carrierName: 'Lufthansa Cargo',
      vesselVoyage: 'LH-781 Freight',
      pol: 'Soekarno-Hatta (CGK)',
      pod: 'Hamburg Airport (HAM)',
      status: 'Submitted',
      createdBy: 'Dewi Lestari (Import Officer)',
      createdAt: '2026-08-01 13:00 WIB',
      updatedBy: 'Bambang Sugianto (Operation Manager)',
      updatedAt: '2026-08-01 15:45 WIB',
    },
  ],
  shipment: [
    {
      id: 'SHP-2026-901',
      shipmentNo: 'SHP-2026-901',
      companyId: 'CMP-8801',
      quotationId: 'QUO-2026-104',
      contractId: 'CTR-2026-088',
      siId: 'SI-2026-081',
      transportMode: 'Ocean Freight (FCL)',
      status: 'In Transit',
      incoterm: 'FOB',
      originPort: 'Tanjung Priok (IDTPP)',
      destinationPort: 'Singapore (SGSIN)',
      etd: '2026-08-01',
      eta: '2026-08-05',
      blNumber: 'MAEU9823411',
      vesselFlight: 'MSC MAYA v.024E',
      totalWeightKg: 18500,
      totalVolumeCbm: 68,
      freightCharge: 4200,
      cargoItems: [
        { description: 'Plywood & Wood Panels', hsCode: '4412.39', qty: 1200, unit: 'CTN', weightKg: 12000 },
        { description: 'Rattan Furniture Sets', hsCode: '9403.89', qty: 250, unit: 'PCS', weightKg: 6500 },
      ],
      createdBy: 'Rizky Pratama (Export Officer)',
      createdAt: '2026-08-01 08:30 WIB',
      updatedBy: 'Bambang Sugianto (Operation Manager)',
      updatedAt: '2026-08-02 11:15 WIB',
    },
    {
      id: 'SHP-2026-902',
      shipmentNo: 'SHP-2026-902',
      companyId: 'CMP-8802',
      quotationId: 'QUO-2026-105',
      contractId: 'CTR-2026-089',
      siId: 'SI-2026-082',
      transportMode: 'Air Freight',
      status: 'Customs Clearance',
      incoterm: 'CIF',
      originPort: 'Soekarno-Hatta Cargo (CGK)',
      destinationPort: 'Hamburg Airport (HAM)',
      etd: '2026-08-02',
      eta: '2026-08-04',
      blNumber: 'AWB-882-99012',
      vesselFlight: 'LH-781 Freight',
      totalWeightKg: 2400,
      totalVolumeCbm: 14.2,
      freightCharge: 8900,
      cargoItems: [
        { description: 'Electronic Components & PCB', hsCode: '8534.00', qty: 50, unit: 'CTN', weightKg: 2400 },
      ],
      createdBy: 'Dewi Lestari (Import Officer)',
      createdAt: '2026-08-02 09:00 WIB',
      updatedBy: 'Hendra Kurniawan (Customs Clearance Officer)',
      updatedAt: '2026-08-03 08:45 WIB',
    },
  ],
  vendorBill: [
    {
      id: 'VBL-2026-302',
      billNo: 'VBL-2026-302',
      companyId: 'CMP-8803',
      shipmentId: 'SHP-2026-901',
      status: 'Unpaid',
      billDate: '2026-07-20',
      dueDate: '2026-08-20',
      totalAmountUsd: 3200,
      notes: 'Maersk Line ocean freight booking invoice. Bank: Deutsche Bank AG Hamburg.',
      createdBy: 'Kevin Nugraha (Pricing & Vendor Officer)',
      createdAt: '2026-07-20 14:10 WIB',
      updatedBy: 'Fajar Ramadhan (AP & Tax Officer)',
      updatedAt: '2026-07-25 10:30 WIB',
    },
  ],
  clientInvoice: [
    {
      id: 'INV-2026-701',
      invoiceNo: 'INV-2026-701',
      companyId: 'CMP-8801',
      shipmentId: 'SHP-2026-901',
      quotationId: 'QUO-2026-104',
      status: 'Sent',
      issueDate: '2026-07-25',
      dueDate: '2026-08-24',
      totalAmountUsd: 5400,
      invoiceItems: [
        { description: 'Freight Charge (IDTPP -> SGSIN)', amountUsd: 4200, taxable: 'Zero-Rated' },
        { description: 'Handling & Export Documentation', amountUsd: 1200, taxable: 'Yes (11%)' },
      ],
      createdBy: 'Anisa Fitriani (AR & Billing Officer)',
      createdAt: '2026-07-25 15:00 WIB',
      updatedBy: 'Sri Wahyuni (Finance Manager)',
      updatedAt: '2026-07-26 09:30 WIB',
    },
    {
      id: 'INV-2026-702',
      invoiceNo: 'INV-2026-702',
      companyId: 'CMP-8802',
      shipmentId: 'SHP-2026-902',
      quotationId: 'QUO-2026-105',
      status: 'Draft',
      issueDate: '2026-08-02',
      dueDate: '2026-09-01',
      totalAmountUsd: 9800,
      invoiceItems: [
        { description: 'Air Freight Charge (CGK -> HAM)', amountUsd: 8900, taxable: 'Zero-Rated' },
        { description: 'Import Handling & Clearance Fee', amountUsd: 900, taxable: 'Yes (11%)' },
      ],
      createdBy: 'Anisa Fitriani (AR & Billing Officer)',
      createdAt: '2026-08-02 16:20 WIB',
      updatedBy: 'Anisa Fitriani (AR & Billing Officer)',
      updatedAt: '2026-08-02 16:20 WIB',
    },
  ],
  accountsReceivable: [
    {
      id: 'AR-2026-001',
      clientInvoiceId: 'INV-2026-701',
      invoiceNumber: 'INV-2026-701',
      companyId: 'CMP-8801',
      customerName: 'PT Samudera Export Indonesia',
      customerCode: 'CMP-8801',
      dueDate: '2026-08-24',
      amount: 5400,
      paidAmount: 0,
      balanceDue: 5400,
      agingCategory: 'Current',
      status: 'Current',
      createdBy: 'Anisa Fitriani (AR & Billing Officer)',
      createdAt: '2026-07-25 15:05 WIB',
      updatedBy: 'Anisa Fitriani (AR & Billing Officer)',
      updatedAt: '2026-07-25 15:05 WIB',
    },
    {
      id: 'AR-2026-002',
      clientInvoiceId: 'INV-2026-702',
      invoiceNumber: 'INV-2026-702',
      companyId: 'CMP-8802',
      customerName: 'Global Trading Pacific Pte Ltd',
      customerCode: 'CMP-8802',
      dueDate: '2026-09-01',
      amount: 9800,
      paidAmount: 0,
      balanceDue: 9800,
      agingCategory: 'Current',
      status: 'Current',
      createdBy: 'Anisa Fitriani (AR & Billing Officer)',
      createdAt: '2026-08-02 16:25 WIB',
      updatedBy: 'Anisa Fitriani (AR & Billing Officer)',
      updatedAt: '2026-08-02 16:25 WIB',
    },
  ],
  userAccount: [
    {
      id: 'USR-001',
      username: 'fdrahman',
      name: 'Fadhlur Rahman',
      email: 'fdrahman@rexcorp.id',
      department: 'ICT',
      position: 'ICT Manager',
      roleName: 'ICT Manager (Full Control)',
      status: 'Active',
      lastActive: '2026-08-03 11:30 WIB',
      createdBy: 'System Init',
      createdAt: '2026-01-01 00:00 WIB',
    },
    {
      id: 'USR-014',
      username: 'adita01',
      name: 'Rudi Aditama',
      email: 'rudi.aditama@rexcorp.id',
      department: 'ICT',
      position: 'ICT Officer',
      roleName: 'ICT Administrator',
      status: 'Active',
      lastActive: '2026-08-03 10:15 WIB',
      createdBy: 'Fadhlur Rahman (ICT Manager)',
      createdAt: '2026-02-10 09:00 WIB',
    },
    {
      id: 'USR-002',
      username: 'sugia01',
      name: 'Bambang Sugianto',
      email: 'bambang.sugianto@rexcorp.id',
      department: 'Operation',
      position: 'Operation Manager',
      roleName: 'Operations Lead',
      status: 'Active',
      lastActive: '2026-08-03 11:00 WIB',
      createdBy: 'Fadhlur Rahman (ICT Manager)',
      createdAt: '2026-01-05 08:30 WIB',
    },
    {
      id: 'USR-003',
      username: 'prata01',
      name: 'Rizky Pratama',
      email: 'rizky.pratama@rexcorp.id',
      department: 'Operation',
      position: 'Export Officer',
      roleName: 'Export Logistics Officer',
      status: 'Active',
      lastActive: '2026-08-03 10:45 WIB',
      createdBy: 'Bambang Sugianto (Operation Manager)',
      createdAt: '2026-01-10 09:00 WIB',
    },
    {
      id: 'USR-004',
      username: 'lesta01',
      name: 'Dewi Lestari',
      email: 'dewi.lestari@rexcorp.id',
      department: 'Operation',
      position: 'Import Officer',
      roleName: 'Import Logistics Officer',
      status: 'Active',
      lastActive: '2026-08-03 09:20 WIB',
      createdBy: 'Bambang Sugianto (Operation Manager)',
      createdAt: '2026-01-12 09:00 WIB',
    },
    {
      id: 'USR-005',
      username: 'kurna01',
      name: 'Hendra Kurniawan',
      email: 'hendra.kurniawan@rexcorp.id',
      department: 'Operation',
      position: 'Customs Clearance Officer',
      roleName: 'Customs Clearance Specialist',
      status: 'Active',
      lastActive: '2026-08-03 11:10 WIB',
      createdBy: 'Bambang Sugianto (Operation Manager)',
      createdAt: '2026-01-15 10:00 WIB',
    },
    {
      id: 'USR-006',
      username: 'prata02',
      name: 'Budi Pratama',
      email: 'budi.pratama@rexcorp.id',
      department: 'Marketing',
      position: 'Marketing Manager',
      roleName: 'Commercial Lead',
      status: 'Active',
      lastActive: '2026-08-03 10:00 WIB',
      createdBy: 'Fadhlur Rahman (ICT Manager)',
      createdAt: '2026-01-05 08:30 WIB',
    },
    {
      id: 'USR-007',
      username: 'saput01',
      name: 'Aditia Saputra',
      email: 'aditia.saputra@rexcorp.id',
      department: 'Marketing',
      position: 'Account Officer',
      roleName: 'Key Account Executive',
      status: 'Active',
      lastActive: '2026-08-03 11:25 WIB',
      createdBy: 'Budi Pratama (Marketing Manager)',
      createdAt: '2026-01-20 09:15 WIB',
    },
    {
      id: 'USR-008',
      username: 'indah01',
      name: 'Maya Indah',
      email: 'maya.indah@rexcorp.id',
      department: 'Marketing',
      position: 'Customer Service Officer',
      roleName: 'CS Logistics Support',
      status: 'Active',
      lastActive: '2026-08-03 08:50 WIB',
      createdBy: 'Budi Pratama (Marketing Manager)',
      createdAt: '2026-01-22 09:30 WIB',
    },
    {
      id: 'USR-009',
      username: 'hiday01',
      name: 'Farhan Hidayat',
      email: 'farhan.hidayat@rexcorp.id',
      department: 'Procurement',
      position: 'Procurement Manager',
      roleName: 'Vendor & Carrier Lead',
      status: 'Active',
      lastActive: '2026-08-03 09:40 WIB',
      createdBy: 'Fadhlur Rahman (ICT Manager)',
      createdAt: '2026-01-05 08:30 WIB',
    },
    {
      id: 'USR-010',
      username: 'nugra01',
      name: 'Kevin Nugraha',
      email: 'kevin.nugraha@rexcorp.id',
      department: 'Procurement',
      position: 'Pricing & Vendor Officer',
      roleName: 'Freight Rate Analyst',
      status: 'Active',
      lastActive: '2026-08-03 10:30 WIB',
      createdBy: 'Farhan Hidayat (Procurement Manager)',
      createdAt: '2026-02-01 09:00 WIB',
    },
    {
      id: 'USR-011',
      username: 'wahyu01',
      name: 'Sri Wahyuni',
      email: 'sri.wahyuni@rexcorp.id',
      department: 'Finance',
      position: 'Finance Manager',
      roleName: 'Financial Controller',
      status: 'Active',
      lastActive: '2026-08-03 11:15 WIB',
      createdBy: 'Fadhlur Rahman (ICT Manager)',
      createdAt: '2026-01-05 08:30 WIB',
    },
    {
      id: 'USR-012',
      username: 'fitri01',
      name: 'Anisa Fitriani',
      email: 'anisa.fitriani@rexcorp.id',
      department: 'Finance',
      position: 'AR & Billing Officer',
      roleName: 'Accounts Receivable Officer',
      status: 'Active',
      lastActive: '2026-08-03 11:05 WIB',
      createdBy: 'Sri Wahyuni (Finance Manager)',
      createdAt: '2026-02-05 09:00 WIB',
    },
    {
      id: 'USR-013',
      username: 'ramad01',
      name: 'Fajar Ramadhan',
      email: 'fajar.ramadhan@rexcorp.id',
      department: 'Finance',
      position: 'AP & Tax Officer',
      roleName: 'Accounts Payable Officer',
      status: 'Active',
      lastActive: '2026-08-03 10:50 WIB',
      createdBy: 'Sri Wahyuni (Finance Manager)',
      createdAt: '2026-02-08 09:00 WIB',
    },
  ],
  role: [
    {
      id: 'ROLE-001',
      name: 'ICT Manager (Full Control)',
      department: 'ICT',
      description: 'System administrator with unrestricted authority across all modules, roles, security policies, and audit logs.',
      authorityScope: 'Full System Control',
      status: 'Active',
    },
    {
      id: 'ROLE-002',
      name: 'Operations Lead',
      department: 'Operation',
      description: 'Oversees shipment bookings, bill of lading documentation, container tracking, and SI creation.',
      authorityScope: 'Department Restricted',
      status: 'Active',
    },
    {
      id: 'ROLE-003',
      name: 'Customs Clearance Specialist',
      department: 'Operation',
      description: 'Manages export-import customs clearance, BEA CUKAI document filing, and HS code validations.',
      authorityScope: 'Department Restricted',
      status: 'Active',
    },
    {
      id: 'ROLE-004',
      name: 'Financial Controller',
      department: 'Finance',
      description: 'Oversees client invoices, vendor bills, cost accruals, accounts receivable, and general ledger postings.',
      authorityScope: 'Department Restricted',
      status: 'Active',
    },
  ],
  moduleControl: [
    {
      id: 'MOD-001',
      name: 'Export & Import Forwarding',
      category: 'Core Operations',
      url: '/logistics/shipments',
      type: 'Operational View',
      status: 'Active',
    },
    {
      id: 'MOD-002',
      name: 'Commercial & Sales',
      category: 'Commercial & Sales',
      url: '/commercial/client-accounts',
      type: 'Operational View',
      status: 'Active',
    },
    {
      id: 'MOD-003',
      name: 'Customs & Compliance',
      category: 'Compliance & Customs',
      url: '/compliance/documents',
      type: 'Operational View',
      status: 'Active',
    },
    {
      id: 'MOD-004',
      name: 'Finance & Accounting',
      category: 'Finance & Revenue',
      url: '/finance/invoices',
      type: 'Operational View',
      status: 'Active',
    },
    {
      id: 'MOD-005',
      name: 'Admin & System Control',
      category: 'System & ICT',
      url: '/admin-settings/users',
      type: 'Core System',
      status: 'Active',
    },
  ],
  auditLog: [
    {
      id: 'LOG-1001',
      timestamp: '2026-08-03 08:30 WIB',
      userName: 'Fadhlur Rahman (ICT Manager)',
      userRole: 'ICT Manager (Full Control)',
      action: 'UPDATE',
      module: 'Admin Settings',
      target: 'User Personnel Matrix',
      details: 'Synchronized all 14 department personnel and access policies for Rexcorp Global Trade.',
      ipAddress: '10.240.0.15',
    },
    {
      id: 'LOG-1002',
      timestamp: '2026-08-03 07:45 WIB',
      userName: 'Rizky Pratama (Export Officer)',
      userRole: 'Export Logistics Officer',
      action: 'CREATE',
      module: 'Freight Forwarding',
      target: 'Shipment #SHP-2026-901',
      details: 'Created ocean freight booking (FCL 40ft) for PT Samudera Export Indonesia.',
      ipAddress: '10.240.0.28',
    },
    {
      id: 'LOG-1003',
      timestamp: '2026-08-02 16:10 WIB',
      userName: 'Hendra Kurniawan (Customs Clearance Officer)',
      userRole: 'Customs Clearance Specialist',
      action: 'UPDATE',
      module: 'Customs Clearance',
      target: 'Customs Doc #PEB-8821',
      details: 'Approved export declaration PEB document filing for Surabaya Port.',
      ipAddress: '10.240.1.04',
    },
    {
      id: 'LOG-1004',
      timestamp: '2026-08-02 14:20 WIB',
      userName: 'Anisa Fitriani (AR & Billing Officer)',
      userRole: 'Accounts Receivable Officer',
      action: 'CREATE',
      module: 'Client Invoicing',
      target: 'Invoice #INV-2026-701',
      details: 'Generated USD 5,400 freight invoice for SHP-2026-901.',
      ipAddress: '10.240.0.99',
    },
  ],
}

// Memory store
const storeData: Record<string, ResourceRecord[]> = { ...initialData }
const listeners = new Set<() => void>()

function notify() {
  listeners.forEach((fn) => fn())
}

export const resourceStore = {
  getAll(resourceName: string): ResourceRecord[] {
    return storeData[resourceName] || []
  },

  getById(resourceName: string, id: string): ResourceRecord | undefined {
    return (storeData[resourceName] || []).find((r) => r.id === id)
  },

  save(resourceName: string, record: ResourceRecord): ResourceRecord {
    if (!storeData[resourceName]) {
      storeData[resourceName] = []
    }

    const timestamp = new Date().toLocaleString('id-ID', { timeZone: 'Asia/Jakarta' }) + ' WIB'
    const activeUser = currentSessionUser

    const existingIndex = storeData[resourceName].findIndex((r) => r.id === record.id)
    if (existingIndex >= 0) {
      const existingRecord = storeData[resourceName][existingIndex]
      const updatedRecord: ResourceRecord = {
        ...existingRecord,
        ...record,
        updatedBy: activeUser,
        updatedAt: timestamp,
      }
      storeData[resourceName][existingIndex] = updatedRecord
      notify()
      return updatedRecord
    } else {
      const newRecord: ResourceRecord = {
        ...record,
        createdBy: record.createdBy || activeUser,
        createdAt: record.createdAt || timestamp,
        updatedBy: activeUser,
        updatedAt: timestamp,
      }
      storeData[resourceName].unshift(newRecord)
      notify()
      return newRecord
    }
  },

  delete(resourceName: string, id: string): void {
    if (!storeData[resourceName]) return
    storeData[resourceName] = storeData[resourceName].filter((r) => r.id !== id)
    notify()
  },

  subscribe(listener: () => void): () => void {
    listeners.add(listener)
    return () => listeners.delete(listener)
  },
}

export function useResourceData(resourceName: string) {
  const [data, setData] = useState<ResourceRecord[]>(() => resourceStore.getAll(resourceName))

  useEffect(() => {
    const unsubscribe = resourceStore.subscribe(() => {
      setData([...resourceStore.getAll(resourceName)])
    })
    return unsubscribe
  }, [resourceName])

  return data
}
