// =============================================================================
// MASTER DATA — ERP-ONE / MASBRO AI
// Scope: Indonesia (base) ↔ China, Singapore, USA, Japan, UAE
// Used by: invoices, quotations, shipments, customs declarations
// Snowflake migration target: tables erp_clients, erp_ports, erp_vessels
// =============================================================================

export type CountryCode = 'ID' | 'CN' | 'SG' | 'US' | 'JP' | 'AE'

export interface ClientCompany {
  id: string
  name: string
  shortName: string
  initials: string
  country: CountryCode
  city: string
  address: string
  postalCode?: string
  email: string
  phone: string
  taxId: string
  tier: 'Priority' | 'Standard' | 'Non-priority'
  industry: string
  currency: string
  creditLimit: number
  arBalance: number
  paymentTerms: string
  bankName: string
  bankAccountNo: string
  swiftCode: string
  contactPerson: string
  contactRole: string
  status: 'Active' | 'On Hold' | 'Inactive'
}

export interface Port {
  locode: string        // UN/LOCODE, e.g. IDJKT
  name: string
  city: string
  country: CountryCode
  coordinates: [number, number] // [lng, lat]
  type: 'sea' | 'air' | 'both'
}

export interface Vessel {
  name: string
  imo: string           // IMO number
  carrier: string
  flag: string
}

// =============================================================================
// CLIENT COMPANIES — 30 companies across 6 countries
// =============================================================================

export const clientCompanies: ClientCompany[] = [
  // ─── INDONESIA (Home / Origin) ─────────────────────────────────────────────
  {
    id: 'ID-001',
    name: 'PT Krakatau Steel (Persero) Tbk',
    shortName: 'Krakatau Steel',
    initials: 'KS',
    country: 'ID',
    city: 'Cilegon',
    address: 'Jl. Industri No.1, Cilegon, Banten',
    postalCode: '42435',
    email: 'procurement@krakatau-steel.co.id',
    phone: '+62-254-571-2001',
    taxId: '01.002.945.0-011.000',
    tier: 'Priority',
    industry: 'Steel Manufacturing',
    currency: 'IDR',
    creditLimit: 7500000000,
    arBalance: 1250000000,
    paymentTerms: 'Net 60 Days',
    bankName: 'Bank Mandiri (Persero) Tbk',
    bankAccountNo: '116-00-0888999-1',
    swiftCode: 'BMRIIDJA',
    contactPerson: 'Hendra Wijaya',
    contactRole: 'VP Procurement & Supply Chain',
    status: 'Active',
  },
  {
    id: 'ID-002',
    name: 'PT Indofood Sukses Makmur Tbk',
    shortName: 'Indofood',
    initials: 'IF',
    country: 'ID',
    city: 'Jakarta',
    address: 'Sudirman Plaza, Indofood Tower Lt. 23, Jl. Jend. Sudirman Kav. 76-78',
    postalCode: '12910',
    email: 'export@indofood.co.id',
    phone: '+62-21-5795-8822',
    taxId: '01.001.234.5-094.000',
    tier: 'Priority',
    industry: 'Food & Beverage Manufacturing',
    currency: 'IDR',
    creditLimit: 5000000000,
    arBalance: 820000000,
    paymentTerms: 'Net 30 Days',
    bankName: 'Bank Central Asia (BCA)',
    bankAccountNo: '001-3988-821',
    swiftCode: 'CENAIDJA',
    contactPerson: 'Budi Santoso',
    contactRole: 'Global Export Manager',
    status: 'Active',
  },
  {
    id: 'ID-003',
    name: 'PT Astra International Tbk',
    shortName: 'Astra International',
    initials: 'AI',
    country: 'ID',
    city: 'Jakarta',
    address: 'Jl. Gaya Motor Raya No.8, Sunter II, Jakarta Utara',
    postalCode: '14330',
    email: 'logistics@astra.co.id',
    phone: '+62-21-6522-555',
    taxId: '01.003.678.9-073.000',
    tier: 'Priority',
    industry: 'Automotive & Heavy Equipment',
    currency: 'IDR',
    creditLimit: 10000000000,
    arBalance: 2400000000,
    paymentTerms: 'Net 45 Days',
    bankName: 'Bank Rakyat Indonesia (BRI)',
    bankAccountNo: '0341-01-000234-30-2',
    swiftCode: 'BRINIDJA',
    contactPerson: 'Ratna Kusuma',
    contactRole: 'Head of Shipping & Logistics',
    status: 'Active',
  },
  {
    id: 'ID-004',
    name: 'PT Unilever Indonesia Tbk',
    shortName: 'Unilever Indonesia',
    initials: 'UL',
    country: 'ID',
    city: 'Tangerang',
    address: 'Grha Unilever, BSD Green Office Park Kav. 3, BSD City',
    postalCode: '15345',
    email: 'supply.chain@unilever.co.id',
    phone: '+62-21-8082-7000',
    taxId: '01.000.156.3-054.000',
    tier: 'Priority',
    industry: 'FMCG / Consumer Goods',
    currency: 'IDR',
    creditLimit: 6000000000,
    arBalance: 450000000,
    paymentTerms: 'Net 30 Days',
    bankName: 'Standard Chartered Bank Indonesia',
    bankAccountNo: '306-0012345-09',
    swiftCode: 'SCBLIDJA',
    contactPerson: 'Dewi Sartika',
    contactRole: 'Inbound Logistics Lead',
    status: 'Active',
  },
  {
    id: 'ID-005',
    name: 'PT Semen Indonesia (Persero) Tbk',
    shortName: 'Semen Indonesia',
    initials: 'SI',
    country: 'ID',
    city: 'Gresik',
    address: 'Jl. Veteran, Gresik, Jawa Timur',
    postalCode: '61122',
    email: 'export@semenindonesia.com',
    phone: '+62-31-398-1732',
    taxId: '01.071.912.3-051.000',
    tier: 'Standard',
    industry: 'Cement & Building Materials',
    currency: 'IDR',
    creditLimit: 3000000000,
    arBalance: 310000000,
    paymentTerms: 'Net 30 Days',
    bankName: 'Bank Negara Indonesia (BNI)',
    bankAccountNo: '008-888-9912',
    swiftCode: 'BBNIIDJA',
    contactPerson: 'Agus Setiawan',
    contactRole: 'Overseas Distribution Supervisor',
    status: 'Active',
  },

  // ─── CHINA ─────────────────────────────────────────────────────────────────
  {
    id: 'CN-001',
    name: 'Midea Group Co., Ltd.',
    shortName: 'Midea Group',
    initials: 'MG',
    country: 'CN',
    city: 'Foshan',
    address: 'No.6 Midea Avenue, Shunde District, Foshan, Guangdong',
    postalCode: '528311',
    email: 'export@midea.com',
    phone: '+86-757-2338-8888',
    taxId: '91440606744027458L',
    tier: 'Priority',
    industry: 'Home Appliances Manufacturing',
    currency: 'USD',
    creditLimit: 500000,
    arBalance: 84500,
    paymentTerms: 'Net 30 Days',
    bankName: 'Bank of China (Guangdong Branch)',
    bankAccountNo: '4782-9011-2234',
    swiftCode: 'BKCHCNBJ400',
    contactPerson: 'Chen Wei',
    contactRole: 'Senior Overseas Trade Director',
    status: 'Active',
  },
  {
    id: 'CN-002',
    name: 'Haier Smart Home Co., Ltd.',
    shortName: 'Haier',
    initials: 'HA',
    country: 'CN',
    city: 'Qingdao',
    address: 'No.1 Haier Road, Laoshan District, Qingdao, Shandong',
    postalCode: '266101',
    email: 'global.logistics@haier.com',
    phone: '+86-532-8893-9999',
    taxId: '91370200132498407G',
    tier: 'Priority',
    industry: 'Electronics & Home Appliances',
    currency: 'USD',
    creditLimit: 600000,
    arBalance: 112000,
    paymentTerms: 'Net 45 Days',
    bankName: 'Industrial and Commercial Bank of China (ICBC)',
    bankAccountNo: '1602-0011-8890',
    swiftCode: 'ICBCCNBJ',
    contactPerson: 'Zhang Lin',
    contactRole: 'Southeast Asia Supply Chain Head',
    status: 'Active',
  },
  {
    id: 'CN-003',
    name: 'Yiwu Jingshen Import & Export Co., Ltd.',
    shortName: 'Yiwu Jingshen',
    initials: 'YJ',
    country: 'CN',
    city: 'Yiwu',
    address: 'Room 1506, Futian Trade Zone, Yiwu, Zhejiang',
    postalCode: '322000',
    email: 'trade@yiwujingshen.com',
    phone: '+86-579-8521-6688',
    taxId: '91330782341234567X',
    tier: 'Standard',
    industry: 'General Trade / Commodities',
    currency: 'USD',
    creditLimit: 150000,
    arBalance: 28500,
    paymentTerms: 'Letter of Credit (L/C)',
    bankName: 'China Construction Bank (CCB)',
    bankAccountNo: '3300-1928-8812',
    swiftCode: 'PCBC2100',
    contactPerson: 'Wang Qiang',
    contactRole: 'General Manager',
    status: 'Active',
  },
  {
    id: 'CN-004',
    name: 'Ningbo Cosco Shipping Supply Chain Management Co., Ltd.',
    shortName: 'COSCO Supply Chain',
    initials: 'CS',
    country: 'CN',
    city: 'Ningbo',
    address: 'No.168 Zhongshan West Road, Jiangbei District, Ningbo, Zhejiang',
    postalCode: '315000',
    email: 'operations@coscosc-nb.com',
    phone: '+86-574-8731-2288',
    taxId: '91330206MA27PWLU1P',
    tier: 'Priority',
    industry: 'Logistics & Supply Chain',
    currency: 'USD',
    creditLimit: 800000,
    arBalance: 145000,
    paymentTerms: 'Net 30 Days',
    bankName: 'Bank of Communications (BOCOM)',
    bankAccountNo: '3310-0988-1123',
    swiftCode: 'COMMCN33',
    contactPerson: 'Li Ming',
    contactRole: 'Ocean Freight Operations VP',
    status: 'Active',
  },
  {
    id: 'CN-005',
    name: 'Shenzhen BYD Auto Industry Co., Ltd.',
    shortName: 'BYD Auto',
    initials: 'BY',
    country: 'CN',
    city: 'Shenzhen',
    address: 'No.3009 BYD Road, Pingshan District, Shenzhen, Guangdong',
    postalCode: '518118',
    email: 'export.logistics@byd.com',
    phone: '+86-755-8988-8888',
    taxId: '91440300192530256G',
    tier: 'Priority',
    industry: 'Electric Vehicles & Battery',
    currency: 'USD',
    creditLimit: 1200000,
    arBalance: 320000,
    paymentTerms: 'Net 60 Days',
    bankName: 'China Merchants Bank (CMB)',
    bankAccountNo: '7559-0012-3344',
    swiftCode: 'CMBCCNBS',
    contactPerson: 'Liu Yang',
    contactRole: 'Global EV Logistics Director',
    status: 'Active',
  },
  {
    id: 'CN-006',
    name: 'Guangzhou Poly Developments and Holdings Group Co., Ltd.',
    shortName: 'Poly Developments',
    initials: 'PD',
    country: 'CN',
    city: 'Guangzhou',
    address: 'Poly Plaza, No.233 Tianhe North Road, Tianhe District, Guangzhou',
    postalCode: '510620',
    email: 'procurement@polygroup.com.cn',
    phone: '+86-20-3833-3333',
    taxId: '91440101735934645P',
    tier: 'Standard',
    industry: 'Real Estate & Construction',
    currency: 'USD',
    creditLimit: 250000,
    arBalance: 42000,
    paymentTerms: 'Net 30 Days',
    bankName: 'Agricultural Bank of China (ABC)',
    bankAccountNo: '4401-2099-3388',
    swiftCode: 'ABCCCNBJ',
    contactPerson: 'Zhao Feng',
    contactRole: 'Materials Procurement Lead',
    status: 'Active',
  },

  // ─── SINGAPORE ─────────────────────────────────────────────────────────────
  {
    id: 'SG-001',
    name: 'Olam International Limited',
    shortName: 'Olam International',
    initials: 'OL',
    country: 'SG',
    city: 'Singapore',
    address: '7 Straits View, Marina One East Tower, #20-01',
    postalCode: '018936',
    email: 'trade@olamgroup.com',
    phone: '+65-6339-4100',
    taxId: '199504676H',
    tier: 'Priority',
    industry: 'Agri-commodities Trading',
    currency: 'USD',
    creditLimit: 750000,
    arBalance: 98000,
    paymentTerms: 'Net 30 Days',
    bankName: 'DBS Bank Ltd',
    bankAccountNo: '003-901234-1',
    swiftCode: 'DBSSSGSG',
    contactPerson: 'Tan Kah Kee',
    contactRole: 'Commodity Logistics Manager',
    status: 'Active',
  },
  {
    id: 'SG-002',
    name: 'Wilmar International Limited',
    shortName: 'Wilmar International',
    initials: 'WI',
    country: 'SG',
    city: 'Singapore',
    address: '56 Neil Road',
    postalCode: '088830',
    email: 'logistics@wilmar-intl.com',
    phone: '+65-6216-0244',
    taxId: '199904785Z',
    tier: 'Priority',
    industry: 'Palm Oil & Agri-Products',
    currency: 'USD',
    creditLimit: 1000000,
    arBalance: 165000,
    paymentTerms: 'Net 30 Days',
    bankName: 'Oversea-Chinese Banking Corporation (OCBC)',
    bankAccountNo: '501-889901-001',
    swiftCode: 'OCBCSGSG',
    contactPerson: 'Melvin Lim',
    contactRole: 'Head of Global Bulk Shipping',
    status: 'Active',
  },
  {
    id: 'SG-003',
    name: 'Pacific International Lines (PIL) Pte. Ltd.',
    shortName: 'PIL Shipping',
    initials: 'PI',
    country: 'SG',
    city: 'Singapore',
    address: 'PIL Building, 140 Cecil Street, #04-00',
    postalCode: '069540',
    email: 'booking@pilship.com',
    phone: '+65-6227-0233',
    taxId: '196700537N',
    tier: 'Priority',
    industry: 'Shipping & Logistics',
    currency: 'USD',
    creditLimit: 850000,
    arBalance: 120000,
    paymentTerms: 'Net 45 Days',
    bankName: 'United Overseas Bank (UOB)',
    bankAccountNo: '101-309-882-9',
    swiftCode: 'UOVBSGSG',
    contactPerson: 'Teo Siong Seng',
    contactRole: 'Line Operations Director',
    status: 'Active',
  },
  {
    id: 'SG-004',
    name: 'YCH Group Pte. Ltd.',
    shortName: 'YCH Group',
    initials: 'YC',
    country: 'SG',
    city: 'Singapore',
    address: '59 Tuas Avenue 11',
    postalCode: '639103',
    email: 'enquiry@ych.com',
    phone: '+65-6861-0011',
    taxId: '196200065K',
    tier: 'Standard',
    industry: 'Integrated Logistics',
    currency: 'USD',
    creditLimit: 300000,
    arBalance: 45000,
    paymentTerms: 'Net 30 Days',
    bankName: 'DBS Bank Ltd',
    bankAccountNo: '072-001122-3',
    swiftCode: 'DBSSSGSG',
    contactPerson: 'Robert Yap',
    contactRole: 'Supply Chain Solutions Head',
    status: 'Active',
  },
  {
    id: 'SG-005',
    name: 'Singapore Technologies Engineering Ltd.',
    shortName: 'ST Engineering',
    initials: 'ST',
    country: 'SG',
    city: 'Singapore',
    address: '1 Ang Mo Kio Electronics Park Road #07-01',
    postalCode: '567710',
    email: 'procurement@stengg.com',
    phone: '+65-6722-1818',
    taxId: '199706274H',
    tier: 'Standard',
    industry: 'Aerospace & Defense Engineering',
    currency: 'USD',
    creditLimit: 500000,
    arBalance: 78000,
    paymentTerms: 'Net 30 Days',
    bankName: 'DBS Bank Ltd',
    bankAccountNo: '015-908234-8',
    swiftCode: 'DBSSSGSG',
    contactPerson: 'Vincent Chong',
    contactRole: 'Global Freight Manager',
    status: 'Active',
  },

  // ─── UNITED STATES ─────────────────────────────────────────────────────────
  {
    id: 'US-001',
    name: 'Cargill Incorporated',
    shortName: 'Cargill',
    initials: 'CA',
    country: 'US',
    city: 'Wayzata',
    address: '15407 McGinty Road West, Wayzata, MN',
    postalCode: '55391',
    email: 'trading@cargill.com',
    phone: '+1-952-742-7575',
    taxId: '41-0447595',
    tier: 'Priority',
    industry: 'Agri-commodities & Food',
    currency: 'USD',
    creditLimit: 1500000,
    arBalance: 210000,
    paymentTerms: 'Net 30 Days',
    bankName: 'JPMorgan Chase Bank, N.A.',
    bankAccountNo: '8890-1234-56',
    swiftCode: 'CHASUS33',
    contactPerson: 'David MacLennan',
    contactRole: 'Global Grain Trade Director',
    status: 'Active',
  },
  {
    id: 'US-002',
    name: 'Caterpillar Export Inc.',
    shortName: 'Caterpillar Export',
    initials: 'CE',
    country: 'US',
    city: 'Peoria',
    address: '100 NE Adams Street, Peoria, IL',
    postalCode: '61629',
    email: 'global.trade@cat.com',
    phone: '+1-309-675-1000',
    taxId: '37-0602140',
    tier: 'Priority',
    industry: 'Heavy Equipment & Mining',
    currency: 'USD',
    creditLimit: 1200000,
    arBalance: 185000,
    paymentTerms: 'Net 45 Days',
    bankName: 'Bank of America, N.A.',
    bankAccountNo: '4450-8812-9011',
    swiftCode: 'BOFAUS3N',
    contactPerson: 'Jim Umpleby',
    contactRole: 'Heavy Machinery Freight Lead',
    status: 'Active',
  },
  {
    id: 'US-003',
    name: 'Dow Chemical International Ltd.',
    shortName: 'Dow Chemical',
    initials: 'DC',
    country: 'US',
    city: 'Midland',
    address: '2030 Dow Center, Midland, MI',
    postalCode: '48674',
    email: 'export.compliance@dow.com',
    phone: '+1-989-636-1000',
    taxId: '38-1285128',
    tier: 'Priority',
    industry: 'Chemical & Petrochemical',
    currency: 'USD',
    creditLimit: 900000,
    arBalance: 130000,
    paymentTerms: 'Net 30 Days',
    bankName: 'Citibank, N.A.',
    bankAccountNo: '3019-2281-00',
    swiftCode: 'CITIUS33',
    contactPerson: 'Jim Fitterling',
    contactRole: 'Hazmat & Tanker Logistics VP',
    status: 'Active',
  },
  {
    id: 'US-004',
    name: 'Walmart Global Sourcing Inc.',
    shortName: 'Walmart Sourcing',
    initials: 'WS',
    country: 'US',
    city: 'Bentonville',
    address: '702 SW 8th Street, Bentonville, AR',
    postalCode: '72716',
    email: 'global.sourcing@walmart.com',
    phone: '+1-479-273-4000',
    taxId: '71-0415188',
    tier: 'Priority',
    industry: 'Retail & Consumer Goods',
    currency: 'USD',
    creditLimit: 2000000,
    arBalance: 340000,
    paymentTerms: 'Net 60 Days',
    bankName: 'Wells Fargo Bank, N.A.',
    bankAccountNo: '1099-2341-889',
    swiftCode: 'WFBIUS6S',
    contactPerson: 'Kathryn McLay',
    contactRole: 'Transpacific Freight Manager',
    status: 'Active',
  },
  {
    id: 'US-005',
    name: 'Mosaic Company (The)',
    shortName: 'The Mosaic Co.',
    initials: 'MC',
    country: 'US',
    city: 'Tampa',
    address: '101 Gordon Drive, Lithia, FL',
    postalCode: '33547',
    email: 'trade@mosaicco.com',
    phone: '+1-800-918-8270',
    taxId: '20-1026454',
    tier: 'Standard',
    industry: 'Fertilizer & Mining',
    currency: 'USD',
    creditLimit: 400000,
    arBalance: 52000,
    paymentTerms: 'Net 30 Days',
    bankName: 'JPMorgan Chase Bank, N.A.',
    bankAccountNo: '9901-2384-11',
    swiftCode: 'CHASUS33',
    contactPerson: 'Joc O\'Rourke',
    contactRole: 'Bulk Commodity Shipping Head',
    status: 'Active',
  },

  // ─── JAPAN ─────────────────────────────────────────────────────────────────
  {
    id: 'JP-001',
    name: 'Toyota Tsusho Corporation',
    shortName: 'Toyota Tsusho',
    initials: 'TT',
    country: 'JP',
    city: 'Nagoya',
    address: 'Nagoya Lucent Tower, 6-1 Ushijima-cho, Nishi-ku, Nagoya',
    postalCode: '451-6014',
    email: 'global.logistics@toyota-tsusho.com',
    phone: '+81-52-584-5000',
    taxId: '5180001010045',
    tier: 'Priority',
    industry: 'General Trading & Automotive',
    currency: 'USD',
    creditLimit: 1000000,
    arBalance: 155000,
    paymentTerms: 'Net 30 Days',
    bankName: 'MUFG Bank, Ltd.',
    bankAccountNo: '001-890123-4',
    swiftCode: 'BOTKJPJT',
    contactPerson: 'Ichiro Suzuki',
    contactRole: 'Global Logistics Division Manager',
    status: 'Active',
  },
  {
    id: 'JP-002',
    name: 'Sumitomo Corporation',
    shortName: 'Sumitomo Corp.',
    initials: 'SC',
    country: 'JP',
    city: 'Tokyo',
    address: 'Harumi Island Triton Square Office Tower Y, 8-11-1 Harumi, Chuo-ku, Tokyo',
    postalCode: '104-8610',
    email: 'trade@sumitomocorp.co.jp',
    phone: '+81-3-5166-6000',
    taxId: '1010001008507',
    tier: 'Priority',
    industry: 'General Trading / Sogo Shosha',
    currency: 'USD',
    creditLimit: 900000,
    arBalance: 118000,
    paymentTerms: 'Net 30 Days',
    bankName: 'Sumitomo Mitsui Banking Corporation (SMBC)',
    bankAccountNo: '654-3210-987',
    swiftCode: 'SMBCJPJT',
    contactPerson: 'Kenji Sato',
    contactRole: 'ASEAN Business Unit GM',
    status: 'Active',
  },
  {
    id: 'JP-003',
    name: 'Marubeni Corporation',
    shortName: 'Marubeni',
    initials: 'MB',
    country: 'JP',
    city: 'Tokyo',
    address: '4-2, Ohtemachi 1-chome, Chiyoda-ku, Tokyo',
    postalCode: '100-8088',
    email: 'shipping@marubeni.com',
    phone: '+81-3-3282-2111',
    taxId: '1010001008712',
    tier: 'Priority',
    industry: 'General Trading & Infrastructure',
    currency: 'USD',
    creditLimit: 850000,
    arBalance: 92000,
    paymentTerms: 'Net 30 Days',
    bankName: 'Mizuho Bank, Ltd.',
    bankAccountNo: '110-98234-5',
    swiftCode: 'MHCBJPJT',
    contactPerson: 'Taro Tanaka',
    contactRole: 'Infrastructure Shipping Lead',
    status: 'Active',
  },
  {
    id: 'JP-004',
    name: 'Mitsui O.S.K. Lines, Ltd.',
    shortName: 'MOL Shipping',
    initials: 'ML',
    country: 'JP',
    city: 'Tokyo',
    address: 'Toranomon Towers Office, 4-1-28 Toranomon, Minato-ku, Tokyo',
    postalCode: '105-8688',
    email: 'customer.service@mol.co.jp',
    phone: '+81-3-3587-6420',
    taxId: '1010001007546',
    tier: 'Standard',
    industry: 'Ocean Shipping & Logistics',
    currency: 'USD',
    creditLimit: 600000,
    arBalance: 64000,
    paymentTerms: 'Net 45 Days',
    bankName: 'MUFG Bank, Ltd.',
    bankAccountNo: '045-88123-9',
    swiftCode: 'BOTKJPJT',
    contactPerson: 'Takeshi Hashimoto',
    contactRole: 'Bulk Carrier Operations GM',
    status: 'Active',
  },
  {
    id: 'JP-005',
    name: 'Nippon Steel Corporation',
    shortName: 'Nippon Steel',
    initials: 'NS',
    country: 'JP',
    city: 'Tokyo',
    address: 'Marunouchi Park Building, 2-6-1 Marunouchi, Chiyoda-ku, Tokyo',
    postalCode: '100-8071',
    email: 'export@nipponsteel.com',
    phone: '+81-3-6867-4111',
    taxId: '7010701013795',
    tier: 'Standard',
    industry: 'Steel Manufacturing',
    currency: 'USD',
    creditLimit: 700000,
    arBalance: 88000,
    paymentTerms: 'Net 30 Days',
    bankName: 'Sumitomo Mitsui Banking Corporation (SMBC)',
    bankAccountNo: '334-1123-88',
    swiftCode: 'SMBCJPJT',
    contactPerson: 'Eiji Hashimoto',
    contactRole: 'Overseas Raw Material Lead',
    status: 'Active',
  },

  // ─── UAE / DUBAI ────────────────────────────────────────────────────────────
  {
    id: 'AE-001',
    name: 'DP World UAE Region LLC',
    shortName: 'DP World',
    initials: 'DP',
    country: 'AE',
    city: 'Dubai',
    address: 'DP World Tower, Ground Level Jafza, Jebel Ali Free Zone',
    postalCode: '17000',
    email: 'operations@dpworld.com',
    phone: '+971-4-881-5555',
    taxId: '100252290100003',
    tier: 'Priority',
    industry: 'Port Operations & Logistics',
    currency: 'USD',
    creditLimit: 1000000,
    arBalance: 140000,
    paymentTerms: 'Net 30 Days',
    bankName: 'Emirates NBD Bank PJSC',
    bankAccountNo: '101-889012-01',
    swiftCode: 'EBIUAE2ADXB',
    contactPerson: 'Sultan Ahmed Bin Sulayem',
    contactRole: 'Terminal Network Manager',
    status: 'Active',
  },
  {
    id: 'AE-002',
    name: 'Agility Logistics UAE LLC',
    shortName: 'Agility Logistics',
    initials: 'AG',
    country: 'AE',
    city: 'Dubai',
    address: 'Plot No. S10114, Jebel Ali Free Zone South',
    postalCode: '18166',
    email: 'middle.east@agility.com',
    phone: '+971-4-881-8166',
    taxId: '100234567800003',
    tier: 'Priority',
    industry: 'Integrated Logistics',
    currency: 'USD',
    creditLimit: 600000,
    arBalance: 75000,
    paymentTerms: 'Net 30 Days',
    bankName: 'First Abu Dhabi Bank (FAB)',
    bankAccountNo: '002-390112-99',
    swiftCode: 'FABUAEAD',
    contactPerson: 'Tarek Sultan',
    contactRole: 'Regional Freight Lead',
    status: 'Active',
  },
  {
    id: 'AE-003',
    name: 'Transworld Group FZCO',
    shortName: 'Transworld Group',
    initials: 'TW',
    country: 'AE',
    city: 'Dubai',
    address: 'Jebel Ali Free Zone, P.O. Box 18166',
    postalCode: '18166',
    email: 'shipping@transworldgroup.com',
    phone: '+971-4-881-2626',
    taxId: '100345678900003',
    tier: 'Standard',
    industry: 'Shipping & Freight Forwarding',
    currency: 'USD',
    creditLimit: 350000,
    arBalance: 41000,
    paymentTerms: 'Net 30 Days',
    bankName: 'Mashreq Bank PSC',
    bankAccountNo: '019-228109-01',
    swiftCode: 'MASQUAE2A',
    contactPerson: 'Ramesh S. Ramakrishnan',
    contactRole: 'Feeder Operations VP',
    status: 'Active',
  },
  {
    id: 'AE-004',
    name: 'Emirates Steel Arkan PJSC',
    shortName: 'Emirates Steel',
    initials: 'ES',
    country: 'AE',
    city: 'Abu Dhabi',
    address: 'Mussafah Industrial Area, P.O. Box 30611',
    postalCode: '30611',
    email: 'procurement@emiratessteel.com',
    phone: '+971-2-449-0500',
    taxId: '100456789000003',
    tier: 'Standard',
    industry: 'Steel Manufacturing',
    currency: 'USD',
    creditLimit: 500000,
    arBalance: 68000,
    paymentTerms: 'Net 30 Days',
    bankName: 'Abu Dhabi Commercial Bank (ADCB)',
    bankAccountNo: '1209-8812-001',
    swiftCode: 'ADCBUAE2A',
    contactPerson: 'Saeed Ghumran Al Remeithi',
    contactRole: 'Raw Materials Purchasing Manager',
    status: 'Active',
  },
  {
    id: 'AE-005',
    name: 'Gulf Petrochem FZC',
    shortName: 'Gulf Petrochem',
    initials: 'GP',
    country: 'AE',
    city: 'Sharjah',
    address: 'Hamriyah Free Zone, Sharjah',
    postalCode: '52244',
    email: 'trading@gulfpetrochem.com',
    phone: '+971-6-526-2626',
    taxId: '100567890100003',
    tier: 'Standard',
    industry: 'Oil & Petrochemical Trading',
    currency: 'USD',
    creditLimit: 400000,
    arBalance: 32000,
    paymentTerms: 'Net 30 Days',
    bankName: 'Habib Bank AG Zurich',
    bankAccountNo: '8810-2299-11',
    swiftCode: 'HBZUUAE2',
    contactPerson: 'Sanjeev Goel',
    contactRole: 'Tanker Chartering Manager',
    status: 'Active',
  },
]

// =============================================================================
// PORTS — UN/LOCODE Reference
// =============================================================================

export const ports: Port[] = [
  // Indonesia
  { locode: 'IDJKT', name: 'Tanjung Priok Port', city: 'Jakarta', country: 'ID', coordinates: [106.8805, -6.1046], type: 'sea' },
  { locode: 'IDJBR', name: 'Tanjung Perak Port', city: 'Surabaya', country: 'ID', coordinates: [112.7298, -7.2060], type: 'sea' },
  { locode: 'IDSRG', name: 'Tanjung Emas Port', city: 'Semarang', country: 'ID', coordinates: [110.4227, -6.9568], type: 'sea' },
  { locode: 'IDBTH', name: 'Batu Ampar Port', city: 'Batam', country: 'ID', coordinates: [104.0457, 1.1225], type: 'sea' },
  { locode: 'IDCGK', name: 'Soekarno-Hatta Int\'l Airport', city: 'Jakarta', country: 'ID', coordinates: [106.6557, -6.1255], type: 'air' },
  { locode: 'IDMDC', name: 'Makassar New Port', city: 'Makassar', country: 'ID', coordinates: [119.4127, -5.1477], type: 'sea' },
  // China
  { locode: 'CNSHA', name: 'Port of Shanghai', city: 'Shanghai', country: 'CN', coordinates: [121.8899, 30.6234], type: 'both' },
  { locode: 'CNNGB', name: 'Port of Ningbo-Zhoushan', city: 'Ningbo', country: 'CN', coordinates: [121.8794, 29.8683], type: 'sea' },
  { locode: 'CNTAO', name: 'Port of Qingdao', city: 'Qingdao', country: 'CN', coordinates: [120.3826, 36.0671], type: 'sea' },
  { locode: 'CNGZU', name: 'Port of Guangzhou (Nansha)', city: 'Guangzhou', country: 'CN', coordinates: [113.5697, 22.7236], type: 'sea' },
  { locode: 'CNSZX', name: 'Shenzhen Yantian Port', city: 'Shenzhen', country: 'CN', coordinates: [114.2636, 22.5614], type: 'sea' },
  // Singapore
  { locode: 'SGSIN', name: 'Port of Singapore (PSA)', city: 'Singapore', country: 'SG', coordinates: [103.8198, 1.2778], type: 'both' },
  // United States
  { locode: 'USLAX', name: 'Port of Los Angeles', city: 'Los Angeles', country: 'US', coordinates: [-118.2717, 33.7454], type: 'both' },
  { locode: 'USNYC', name: 'Port of New York / Newark', city: 'New York', country: 'US', coordinates: [-74.0479, 40.6840], type: 'both' },
  { locode: 'USSEA', name: 'Port of Seattle-Tacoma', city: 'Seattle', country: 'US', coordinates: [-122.3779, 47.5499], type: 'sea' },
  { locode: 'USORD', name: 'O\'Hare International Airport', city: 'Chicago', country: 'US', coordinates: [-87.9073, 41.9742], type: 'air' },
  // Japan
  { locode: 'JPYOK', name: 'Port of Yokohama', city: 'Yokohama', country: 'JP', coordinates: [139.6503, 35.4437], type: 'both' },
  { locode: 'JPOSE', name: 'Port of Osaka', city: 'Osaka', country: 'JP', coordinates: [135.4351, 34.6550], type: 'sea' },
  { locode: 'JPNGO', name: 'Port of Nagoya', city: 'Nagoya', country: 'JP', coordinates: [136.8941, 35.0745], type: 'sea' },
  { locode: 'JPNRT', name: 'Narita International Airport', city: 'Tokyo', country: 'JP', coordinates: [140.3864, 35.7647], type: 'air' },
  // UAE
  { locode: 'AEJEA', name: 'Jebel Ali Port (JAXC)', city: 'Dubai', country: 'AE', coordinates: [55.0272, 24.9857], type: 'both' },
  { locode: 'AEDXB', name: 'Dubai International Airport', city: 'Dubai', country: 'AE', coordinates: [55.3644, 25.2532], type: 'air' },
  { locode: 'AEAUH', name: 'Port of Abu Dhabi (Khalifa)', city: 'Abu Dhabi', country: 'AE', coordinates: [54.6278, 24.8029], type: 'sea' },
]

// =============================================================================
// VESSELS — Real-sounding ocean vessels
// =============================================================================

export const vessels: Vessel[] = [
  { name: 'OOCL INDONESIA', imo: '9776200', carrier: 'OOCL', flag: 'HK' },
  { name: 'OOCL JAKARTA', imo: '9776212', carrier: 'OOCL', flag: 'HK' },
  { name: 'MSC SINGAPORE', imo: '9778542', carrier: 'MSC', flag: 'PA' },
  { name: 'MAERSK JAKARTA', imo: '9619907', carrier: 'Maersk', flag: 'DK' },
  { name: 'MAERSK SENTOSA', imo: '9619919', carrier: 'Maersk', flag: 'DK' },
  { name: 'EVER GIVEN', imo: '9811000', carrier: 'Evergreen', flag: 'PA' },
  { name: 'EVER GREET', imo: '9820139', carrier: 'Evergreen', flag: 'PA' },
  { name: 'COSCO SHIPPING UNIVERSE', imo: '9757187', carrier: 'COSCO', flag: 'CN' },
  { name: 'COSCO INDONESIA', imo: '9757199', carrier: 'COSCO', flag: 'CN' },
  { name: 'ONE AQUILA', imo: '9741384', carrier: 'ONE', flag: 'JP' },
  { name: 'ONE APUS', imo: '9741396', carrier: 'ONE', flag: 'JP' },
  { name: 'PIL SINGAPORE', imo: '9826374', carrier: 'PIL', flag: 'SG' },
  { name: 'HMM ALGECIRAS', imo: '9863297', carrier: 'HMM', flag: 'KR' },
  { name: 'CMA CGM MARCO POLO', imo: '9454450', carrier: 'CMA CGM', flag: 'MT' },
  { name: 'YANG MING WITNESS', imo: '9762956', carrier: 'Yang Ming', flag: 'TW' },
]

// =============================================================================
// COMMODITIES — Freight forwarding goods
// =============================================================================

export const commodities = [
  { name: 'Consumer Electronics', hsCode: '8471.30', unit: 'CTN', tempControl: false },
  { name: 'Home Appliances', hsCode: '8516.50', unit: 'SET', tempControl: false },
  { name: 'Steel Products (HRC Coil)', hsCode: '7208.36', unit: 'MT', tempControl: false },
  { name: 'Palm Oil (Crude)', hsCode: '1511.10', unit: 'MT', tempControl: false },
  { name: 'Instant Noodles', hsCode: '1902.30', unit: 'CTN', tempControl: false },
  { name: 'Automotive Parts', hsCode: '8708.99', unit: 'PCS', tempControl: false },
  { name: 'Chemical Fertilizer (Urea)', hsCode: '3102.10', unit: 'MT', tempControl: false },
  { name: 'Cement (Portland)', hsCode: '2523.29', unit: 'MT', tempControl: false },
  { name: 'Rubber Gloves (Medical)', hsCode: '4015.11', unit: 'CTN', tempControl: false },
  { name: 'Frozen Shrimp', hsCode: '0306.17', unit: 'KGS', tempControl: true },
  { name: 'Coffee Beans (Green)', hsCode: '0901.11', unit: 'MT', tempControl: false },
  { name: 'Cocoa Beans', hsCode: '1801.00', unit: 'MT', tempControl: false },
  { name: 'Industrial Machinery', hsCode: '8479.89', unit: 'SET', tempControl: false },
  { name: 'Pharmaceutical Products', hsCode: '3004.90', unit: 'CTN', tempControl: true },
  { name: 'Garments & Apparel', hsCode: '6110.20', unit: 'PCS', tempControl: false },
  { name: 'Footwear', hsCode: '6403.99', unit: 'PRS', tempControl: false },
  { name: 'Paper & Cardboard', hsCode: '4810.19', unit: 'MT', tempControl: false },
  { name: 'Crude Oil (Condensate)', hsCode: '2709.00', unit: 'BBL', tempControl: false },
  { name: 'Mining Equipment', hsCode: '8430.50', unit: 'SET', tempControl: false },
  { name: 'Fishery Products (Tuna)', hsCode: '1604.14', unit: 'CTN', tempControl: true },
]

// =============================================================================
// SHIPPING SERVICES
// =============================================================================

export const serviceTypes = [
  { code: 'FCL-20GP', label: 'FCL 20\' General Purpose', mode: 'sea' as const },
  { code: 'FCL-40GP', label: 'FCL 40\' General Purpose', mode: 'sea' as const },
  { code: 'FCL-40HC', label: 'FCL 40\' High Cube', mode: 'sea' as const },
  { code: 'FCL-20RF', label: 'FCL 20\' Reefer', mode: 'sea' as const },
  { code: 'LCL', label: 'LCL / Groupage', mode: 'sea' as const },
  { code: 'AIR-GENERAL', label: 'Air Freight (General)', mode: 'air' as const },
  { code: 'AIR-EXPRESS', label: 'Air Freight (Express)', mode: 'air' as const },
  { code: 'LAND-FTL', label: 'Land Transport (FTL)', mode: 'land' as const },
  { code: 'LAND-LTL', label: 'Land Transport (LTL)', mode: 'land' as const },
  { code: 'CCS', label: 'Customs Clearance Service', mode: 'customs' as const },
]

// =============================================================================
// HELPERS
// =============================================================================

export function getClientById(id: string): ClientCompany | undefined {
  return clientCompanies.find((c) => c.id === id)
}

export function getClientsByCountry(country: CountryCode): ClientCompany[] {
  return clientCompanies.filter((c) => c.country === country)
}

export function getPortByLocode(locode: string): Port | undefined {
  return ports.find((p) => p.locode === locode)
}

export function randomItem<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]
}
